from nemoir_runtime.canonical import (
    parse_json_strict as parse_json_strict,
)
from nemoir_runtime.canonical import (
    sha256_tag as sha256_tag,
)
from nemoir_runtime.canonical import (
    to_canonical_bytes as to_canonical_bytes,
)
from nemoir_runtime.canonical import (
    to_canonical_str as to_canonical_str,
)
from nemoir_runtime.capabilities import (
    CAPABILITY_CATALOG,
    CapabilityParam,
    CapabilityParamType,
    CapabilitySpec,
    get_capability,
    required_param_names,
)
from nemoir_runtime.errors import (
    DataUnavailableError,
    MaxStepsExceededError,
    MissingCapabilityError,
    ModelOutputValidationError,
    ModelProviderError,
    NemoIRRuntimeError,
    NoTransitionMatchedError,
    PolicyDeniedError,
    PolicyEvaluationError,
    StageOutputValidationError,
    ToolInvocationError,
    ToolValidationError,
    WorkflowTimeoutError,
    WorkflowValidationError,
)
from nemoir_runtime.events import (
    WorkflowEvent,
    WorkflowEventChannel,
    WorkflowEventEmitter,
    WorkflowEventKind,
    WorkflowEventSink,
)
from nemoir_runtime.models import (
    LiteLLMModelAdapter,
    ModelAdapter,
    ModelRequest,
    ModelResponse,
    ModelRouter,
    ModelSpec,
    ModelStageExecutor,
    ModelStreamChunk,
    ModelStreamingAdapter,
    ModelToolCall,
    OpenAIResponsesModelAdapter,
    supports_streaming,
)
from nemoir_runtime.runtime import (
    DeterministicStageExecutor,
    ExprSpec,
    GuardSpec,
    InputSpec,
    PolicySpec,
    ReadSpec,
    RefSpec,
    RequiredCapabilitySpec,
    RunOptions,
    StageContext,
    StageExecutionSpec,
    StageExecutor,
    StageSpec,
    TransitionSpec,
    TriggerSpec,
    WorkflowManifest,
    WorkflowResult,
    WorkflowRuntime,
    WorkflowState,
    WriteSpec,
)
from nemoir_runtime.tools import (
    Tool,
    ToolContext,
    ToolRegistry,
    tool,
)
from nemoir_runtime.trace import (
    HostProvenance,
    ModelDescriptor,
    NoOpTraceRecorder,
    TraceConfig,
    TraceError,
    TraceRecorder,
    TraceValue,
    VerificationReport,
    load_generated_provenance,
    read_archive_entries,
    resolve_recorder,
    resolve_trace_recorder,
    safe_model_descriptor,
    verify_archive,
)

__all__ = [
    "CAPABILITY_CATALOG",
    "CapabilityParam",
    "CapabilityParamType",
    "CapabilitySpec",
    "DataUnavailableError",
    "DeterministicStageExecutor",
    "ExprSpec",
    "GuardSpec",
    "HostProvenance",
    "InputSpec",
    "LiteLLMModelAdapter",
    "MaxStepsExceededError",
    "MissingCapabilityError",
    "ModelAdapter",
    "ModelDescriptor",
    "ModelOutputValidationError",
    "ModelProviderError",
    "ModelRequest",
    "ModelResponse",
    "ModelRouter",
    "ModelSpec",
    "ModelStageExecutor",
    "ModelStreamChunk",
    "ModelStreamingAdapter",
    "ModelToolCall",
    "NemoIRRuntimeError",
    "NoOpTraceRecorder",
    "NoTransitionMatchedError",
    "OpenAIResponsesModelAdapter",
    "PolicyDeniedError",
    "PolicyEvaluationError",
    "PolicySpec",
    "ReadSpec",
    "RefSpec",
    "RequiredCapabilitySpec",
    "RunOptions",
    "StageContext",
    "StageExecutionSpec",
    "StageExecutor",
    "StageOutputValidationError",
    "StageSpec",
    "Tool",
    "ToolContext",
    "ToolInvocationError",
    "ToolRegistry",
    "ToolValidationError",
    "TraceConfig",
    "TraceError",
    "TraceRecorder",
    "TraceValue",
    "TransitionSpec",
    "TriggerSpec",
    "VerificationReport",
    "WorkflowManifest",
    "WorkflowResult",
    "WorkflowRuntime",
    "WorkflowState",
    "WorkflowTimeoutError",
    "WorkflowValidationError",
    "WriteSpec",
    "get_capability",
    "load_generated_provenance",
    "parse_json_strict",
    "read_archive_entries",
    "required_param_names",
    "resolve_recorder",
    "resolve_trace_recorder",
    "safe_model_descriptor",
    "sha256_tag",
    "supports_streaming",
    "to_canonical_bytes",
    "to_canonical_str",
    "tool",
    "verify_archive",
]

# Extended with Phase 5 event primitives (re-exported for convenience).
# Advanced users may import directly from nemoir_runtime.events.
__all__ += [
    "WorkflowEvent",
    "WorkflowEventChannel",
    "WorkflowEventEmitter",
    "WorkflowEventKind",
    "WorkflowEventSink",
]
